#!/usr/bin/env python3
"""Discover, disassemble and round-trip the 68000 side of the cartridge.

  python3 tools/disasm68k.py discover           find 68000 code, print stats
  python3 tools/disasm68k.py fn 0x3f0           disassemble one function
  python3 tools/disasm68k.py emit --verify      emit listing, reassemble, diff

Everything is addressed by cartridge offset; see tools/m68k/analyze.py for why.
"""

import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mars                                          # noqa: E402
from m68k.analyze import Analyzer, to_offset         # noqa: E402
from m68k.decode import decode, INVALID              # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
AS = "m68k-elf-as"
OBJCOPY = "m68k-elf-objcopy"
DEFAULT_ROM = "roms/Knuckles' Chaotix (JU) (32X) [!].32x"
RELATIVE = ("bra", "bsr", "b", "db")


def label_for(off):
    return f"S_{off:06X}"


def analyse(rom_path, sweep=True):
    rom = mars.Rom(rom_path)
    az = Analyzer(rom.data)

    # The 68000 exception vector table is 64 long words at offset 0. Vector 0 is
    # the initial stack pointer, not code; the rest are entry points, and the
    # whole table is data that must never be disassembled.
    az.mark_data(0, "long", 4)
    for i in range(1, 64):
        a = i * 4
        az.mark_data(a, "long", 4)
        t = to_offset(rom.u32(a), len(rom.data))
        if t is not None:
            az.add_function(t, f"vector {i}")
    az.mark_data(0x100, "byte", 0x100)      # Mega Drive header
    az.mark_data(0x3C0, "byte", 0x30)       # MARS header
    az.run()

    # Both sweeps to a fixpoint together: a handler found by one is code the
    # other has not seen yet, and an installation site can sit inside it.
    if sweep:
        for _ in range(16):
            if not (az.scan_after_returns() + az.scan_installed_handlers()):
                break
            az.run()
    return rom, az


def render(ins, labels):
    """Instruction text with relative operands turned into labels.

    A target that falls *inside* another instruction cannot be given a label —
    these tables index from an origin that deliberately overlaps the preceding
    branch — so it stays a numeric address. That still reassembles correctly:
    the listing is laid out at address 0, so an absolute expression and the
    cartridge offset are the same number, and gas recomputes the displacement.
    """
    ops = ins.ops

    def sub_pc(m):
        t = int(m.group(1), 16)
        return f"%pc@({label_for(t)}" if t in labels else m.group(0)

    ops = re.sub(r"%pc@\(0x([0-9a-f]+)", sub_pc, ops)
    if ins.target is not None and ins.mnem.startswith(RELATIVE):
        if ins.target in labels:
            ops = ops.replace(f"0x{ins.target:x}", label_for(ins.target))
    return f"{ins.mnem} {ops}" if ops else ins.mnem


def collect_labels(az, rom):
    want = set()
    for off in az.code:
        ins = az.insns[off]
        if ins.target is not None and ins.mnem.startswith(RELATIVE):
            want.add(ins.target)
        for m in re.finditer(r"%pc@\(0x([0-9a-f]+)", ins.ops):
            want.add(int(m.group(1), 16))
    want |= az.func_entries | az.leaders
    return {w for w in want if 0 <= w < len(rom.data)}


def emit(rom, az, labels, demoted=frozenset()):
    out = ["| Knuckles' Chaotix - 68000 side, generated by tools/disasm68k.py",
           "| Cartridge offsets; do not edit by hand.",
           "\t.text", "\t.align 2", ""]
    data = rom.data
    off = 0
    n = len(data)
    pending = []

    def flush():
        while pending:
            chunk = pending[:16]
            del pending[:16]
            out.append("\t.byte\t" + ",".join(f"0x{b:02x}" for b in chunk))

    while off < n:
        if off in labels:
            flush()
            out.append(f"{label_for(off)}:")
        ins = az.insns.get(off)
        if ins is not None and ins.kind != INVALID and off not in demoted:
            flush()
            try:
                e = decode(az.fetch, off, emit=True)
            except IndexError:
                e = ins
            out.append("\t" + render(e, labels))
            off += ins.size
            continue
        pending.append(data[off])
        off += 1
        if off in labels:
            flush()
    flush()
    out.append("")
    return "\n".join(out)


def cmd_discover(args):
    rom, az = analyse(args.rom)
    s = az.stats()
    print(f"functions       : {s['functions']:,}")
    print(f"basic blocks    : {s['blocks']:,}")
    print(f"instructions    : {s['insns']:,}  ({s['code_bytes']:,} bytes)")
    print(f"unresolved      : {s['unresolved']:,} indirect transfers")
    print(f"ROM coverage    : {100.0 * s['code_bytes'] / len(rom.data):.1f}% "
          f"of {len(rom.data) // 1024} KB")
    big = sorted(az.funcs.values(), key=lambda f: -f.size())[:12]
    print("\nlargest functions:")
    for f in big:
        print(f"  0x{f.start:06X}  {f.size():6,} bytes  {len(f.blocks):4} blocks  "
              f"{len(az.xrefs.get(f.start, ())):3} xrefs")
    from collections import Counter
    print("\nentry reasons:", dict(Counter(az.entry_reasons.values()).most_common(8)))


# Reached from the table the 32X adapter supplies at 0x000000, which nothing in
# the cartridge names — so the front end is right not to have them, and
# src/gen68k.c assembles the ones the game uses. Everything else the 68000
# executes is the cartridge's own and should be discoverable.
ADAPTER_STUBS = (0x8802A2, 0x8802AE)


def cmd_coverage(args):
    """Does the front end have every instruction the 68000 actually executes?

    The SH-2 side has answered this since `tools/diffsh2.py` existed, and the
    68000 side had not been asked. The first time it was, 44 addresses came back
    — the whole vertical interrupt handler among them, because the only path to
    it is a pointer the engine writes into work RAM at run time.

    A trace is evidence, not proof: it can only find code that some run reached.
    Nothing here is asserted from it — it names addresses, and discovery has to
    reach them on its own terms or not at all. The corollary is that a longer
    run asks a harder question, and the default 300-frame trace is a short one:

        ./build/mars --frames 2000 --trace68k /tmp/long.txt \\
            --trace68k-lines 40000000
        python3 tools/disasm68k.py coverage --trace /tmp/long.txt

    which is 23.5 million instructions and 5 GB, and where the 245 addresses
    listed in docs/roadmap.md come from.
    """
    rom, az = analyse(args.rom)
    print(f"front end: {len(az.code):,} instruction offsets")

    # "Covered" has to mean the recompiler can reach it, not just that the
    # disassembler knows the bytes. A block discovery traced but that no
    # function entry reaches falls out of `funcs`, so it is in the listing and
    # in `code` — this check passed — and yet has no row in the dispatch table,
    # which is a hole only the translated build ever falls into. 3,858 of 7,943
    # blocks were in that state, and `--recomp` was spending nine tenths of a
    # million hand-overs to the interpreter on one of them.
    owned = {b for f in az.funcs.values() for b in f.blocks}
    orphans = sorted(set(az.blocks) - owned)
    print(f"  blocks: {len(az.blocks):,} traced, {len(owned):,} owned by a "
          f"function" + (f", ORPHANED {len(orphans)}" if orphans else ""))
    for off in orphans[:12]:
        print(f"      0x{off:06X}")

    pat = re.compile(r"CPU  ([0-9a-f]{6})  ")
    bad = 0
    for path in (args.ref, args.trace):
        if not os.path.exists(path):
            print(f"  {path}: not present, skipped")
            continue
        seen = {}
        with open(path) as f:
            for line in f:
                m = pat.search(line)
                if m:
                    a = int(m.group(1), 16)
                    seen[a] = seen.get(a, 0) + 1
        counts = dict(cartridge=0, ram=0, adapter=0, banked=0)
        missing = {}
        for a, n in seen.items():
            if a >= 0xFF0000:
                counts["ram"] += 1
            elif a < 0x100 or a in ADAPTER_STUBS:
                counts["adapter"] += 1
            elif 0x900000 <= a < 0xA00000:
                counts["banked"] += 1        # bank register decides; not static
            elif to_offset(a, len(rom.data)) in az.code:
                counts["cartridge"] += 1
            else:
                missing[a] = n
        print(f"  {path}: {len(seen):,} distinct PC(s) — "
              + ", ".join(f"{k} {v:,}" for k, v in counts.items())
              + (f", MISSING {len(missing)}" if missing else ", all covered"))
        for a in sorted(missing)[:24]:
            print(f"      0x{a:06X}  x{missing[a]:,}")
        bad += len(missing)
    return 1 if bad or orphans else 0


def cmd_fn(args):
    rom, az = analyse(args.rom)
    off = int(args.addr, 0)
    fn = az.funcs.get(off)
    if not fn:
        print(f"no function at offset 0x{off:06X}")
        return 1
    print(f"function 0x{fn.start:06X}  {fn.size()} bytes, {len(fn.blocks)} blocks "
          f"[{az.entry_reasons.get(off, '')}]")
    for b in sorted(fn.blocks.values(), key=lambda b: b.start):
        print(f"\n .block 0x{b.start:06X}")
        for ins in b.insns:
            raw = " ".join(f"{rom.u16(ins.addr + i):04x}"
                           for i in range(0, ins.size, 2))
            print(f"  {ins.addr:06X}: {raw:<20} {ins.text()}")
    return 0


def cmd_emit(args):
    rom, az = analyse(args.rom)
    os.makedirs(args.outdir, exist_ok=True)
    labels = collect_labels(az, rom)
    # Some tables index from an origin that deliberately overlaps the tail of
    # the preceding instruction, so a needed label can land mid-instruction.
    # There is nowhere to put a label inside an instruction, and gas reads a
    # bare constant in %pc@() as the displacement rather than an address, so
    # neither a symbol nor a number works. Emit the overlapped instruction as
    # raw bytes instead: the label then sits on a byte boundary, and the output
    # is identical either way.
    demoted = set()
    for off, ins in az.insns.items():
        if off not in az.code:
            continue
        if labels & set(range(off + 1, off + ins.size)):
            demoted.add(off)
        elif decode(az.fetch, off, emit=True).lossy:
            demoted.add(off)      # unused immediate half-word holds junk
    if demoted:
        print(f"    {len(demoted)} instruction(s) overlapped by a table origin; "
              f"emitted as bytes")
    src = os.path.join(args.outdir, "m68k_rom.s")
    with open(src, "w") as f:
        f.write(emit(rom, az, labels, demoted))
    print(f"{len(az.code):,} insns, {len(labels):,} labels -> {src}")
    if not args.verify:
        return 0
    obj = os.path.join(args.outdir, "m68k_rom.o")
    binf = os.path.join(args.outdir, "m68k_rom.bin")
    try:
        subprocess.run([AS, "-m68000", "-o", obj, src], check=True)
        subprocess.run([OBJCOPY, "-O", "binary", obj, binf], check=True)
    except subprocess.CalledProcessError:
        print("    ASSEMBLY FAILED")
        return 1
    got = open(binf, "rb").read()
    if got == rom.data:
        print(f"    round-trip OK — {len(got):,} bytes identical")
        return 0
    bad = [i for i in range(min(len(got), len(rom.data))) if got[i] != rom.data[i]]
    print(f"    MISMATCH: {len(got):,} vs {len(rom.data):,} bytes, "
          f"{len(bad):,} differing")
    for i in bad[:12]:
        print(f"      0x{i:06X}: rom {rom.data[i]:02X}  asm {got[i]:02X}")
    return 1


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--rom", default=DEFAULT_ROM)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("discover")
    f = sub.add_parser("fn")
    f.add_argument("addr")
    e = sub.add_parser("emit")
    e.add_argument("--verify", action="store_true")
    e.add_argument("--outdir", default="build")
    c = sub.add_parser("coverage")
    c.add_argument("--ref", default="build/ref68k.txt")
    c.add_argument("--trace", default="build/trace68k.txt")
    args = p.parse_args()
    return {"discover": cmd_discover, "fn": cmd_fn, "emit": cmd_emit,
            "coverage": cmd_coverage}[args.cmd](args) or 0


if __name__ == "__main__":
    sys.exit(main())
