#!/usr/bin/env python3
"""Emit a reassemblable SH-2 listing, and prove it round-trips byte for byte.

The listing is the real deliverable of the SH-2 front end: it is the point at
which "we think this is code" stops being an opinion and becomes checkable. If
`sh-elf-as` turns the emitted source back into the exact bytes the cartridge
holds, then every classification decision — code vs literal pool vs jump table,
every operand, every branch target — was right.

PC-relative operands are emitted as *labels*, never as the raw displacement the
instruction encodes. GNU as treats `@(disp,pc)` operands as target addresses and
recomputes the displacement itself, so feeding it the original number would
silently shift every literal reference.

  python3 tools/emit_asm.py                 write build/sh2_sdram.s (+ overlays)
  python3 tools/emit_asm.py --verify        assemble it and diff against the ROM
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mars                                    # noqa: E402
from disasm import analyse, OVERLAYS, DEFAULT_ROM   # noqa: E402
from sh2.decode import R                       # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.join(HERE, "..", "toolchain", "sh-elf", "bin")
AS = os.path.join(TOOLS, "sh-elf-as")
OBJCOPY = os.path.join(TOOLS, "sh-elf-objcopy")


def label_for(addr):
    return f"L_{addr:08X}"


class Emitter:
    def __init__(self, az, img, lo, hi, title):
        self.az = az
        self.img = img
        self.lo = lo
        self.hi = hi
        self.title = title
        self.labels = self._collect_labels()

    def _collect_labels(self):
        """Every address the listing has to be able to name."""
        want = set()

        def add(a):
            if a is not None and self.lo <= a < self.hi:
                want.add(a)

        for addr in self.az.code:
            if not (self.lo <= addr < self.hi):
                continue
            ins = self.az.insns[addr]
            add(ins.target)
            if ins.pool:
                add(ins.pool[0])
            if ins.mnem == "mova":
                add(ins.imm)
        for a in self.az.leaders:
            add(a)
        for a in self.az.func_entries:
            add(a)
        for t in self.az.tables.values():
            add(t.base)
            for ea, tgt in t.entries:
                add(ea)
                add(tgt)
        return want

    def render(self, ins):
        """Instruction text with symbolic operands where the encoding is relative.

        Returns None when the operand cannot be named — a PC-relative reference
        that leaves the emitted region has no label to point at, and emitting
        its absolute address would either not assemble or silently re-encode to
        something else. The caller falls back to a raw word.
        """
        def inside(a):
            return a is not None and self.lo <= a < self.hi

        if ins.target is not None:
            return f"{ins.mnem}\t{label_for(ins.target)}" if inside(ins.target) else None
        if ins.pool:
            return (f"{ins.mnem}\t{label_for(ins.pool[0])},{R(ins.rn)}"
                    if inside(ins.pool[0]) else None)
        if ins.mnem == "mova":
            return f"mova\t{label_for(ins.imm)},r0" if inside(ins.imm) else None
        return ins.text()

    def emit(self):
        out = [
            f"! {self.title}",
            "! Generated by tools/emit_asm.py — do not edit by hand.",
            "\t.section .text",
            "\t.align 2",
            "",
        ]
        az, img = self.az, self.img
        addr = self.lo
        pending = []          # accumulated raw bytes with no classification

        def flush():
            while pending:
                chunk, del_ = pending[:16], pending[16:]
                out.append("\t.byte\t" + ",".join(f"0x{b:02x}" for b in chunk))
                pending[:] = del_

        while addr < self.hi:
            if addr in self.labels:
                flush()
                out.append(f"{label_for(addr)}:")

            # A literal pool the tracer speculatively fell into is data, not
            # code: the pool reference comes from a real instruction, whereas
            # the fallthrough edge may be unreachable in practice.
            if addr in az.code and addr not in az.data_firm:
                flush()
                ins = az.insns[addr]
                text = self.render(ins)
                out.append(f"\t{text}" if text else f"\t.short\t0x{ins.word:04x}")
                addr += 2
                continue

            kind = az.data.get(addr)
            if kind == "long" and addr % 4 == 0 and img.readable(addr, 4):
                flush()
                out.append(f"\t.long\t0x{img.u32(addr):08x}")
                addr += 4
                continue
            if kind == "short" and addr % 2 == 0 and img.readable(addr, 2):
                flush()
                out.append(f"\t.short\t0x{img.u16(addr):04x}")
                addr += 2
                continue

            pending.append(img.u8(addr))
            addr += 1
            # Keep runs from swallowing an address that needs its own label.
            if addr in self.labels:
                flush()
        flush()
        out.append("")
        return "\n".join(out)


def assemble(src_path, out_bin):
    obj = out_bin + ".o"
    subprocess.run([AS, "-big", "-isa=sh2", "-o", obj, src_path], check=True)
    subprocess.run([OBJCOPY, "-O", "binary", obj, out_bin], check=True)
    with open(out_bin, "rb") as f:
        return f.read()


def diff_report(want, got, base, limit=10):
    if len(want) != len(got):
        print(f"    SIZE MISMATCH: expected {len(want)}, got {len(got)}")
    bad = [i for i in range(min(len(want), len(got))) if want[i] != got[i]]
    print(f"    {len(bad):,} differing bytes")
    for i in bad[:limit]:
        print(f"      0x{base + i:08X}: rom {want[i]:02X}  asm {got[i]:02X}")
    return bad


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--rom", default=DEFAULT_ROM)
    p.add_argument("--verify", action="store_true",
                   help="assemble the listing and compare against the cartridge")
    p.add_argument("--outdir", default="build")
    args = p.parse_args()

    rom, h, img, az = analyse(args.rom)
    os.makedirs(args.outdir, exist_ok=True)

    regions = [(mars.SDRAM_BASE + h.sh2_dst, h.sh2_size, "sh2_sdram",
                rom.sdram_image(), "SH-2 SDRAM image (MARS header block)")]
    for dest, off, size, why in OVERLAYS:
        regions.append((dest, size, f"sh2_overlay_{dest:08x}",
                        rom.data[off:off + size], f"SH-2 overlay: {why}"))

    ok = True
    for base, size, name, original, title in regions:
        src = os.path.join(args.outdir, name + ".s")
        em = Emitter(az, img, base, base + size, title)
        with open(src, "w") as f:
            f.write(em.emit())
        ninsn = sum(1 for a in az.code if base <= a < base + size)
        print(f"{name}: 0x{base:08X}+0x{size:X}  "
              f"{ninsn:,} insns, {len(em.labels):,} labels -> {src}")

        if args.verify:
            try:
                got = assemble(src, os.path.join(args.outdir, name + ".bin"))
            except subprocess.CalledProcessError:
                print("    ASSEMBLY FAILED")
                ok = False
                continue
            if got == original:
                print(f"    round-trip OK — {len(got):,} bytes identical")
            else:
                ok = False
                diff_report(original, got, base)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
