#!/usr/bin/env python3
"""Recompile the discovered 68000 code to C.

  python3 tools/recompile68k.py            write build/m68k_recomp.c
  python3 tools/recompile68k.py --build    also compile it for this machine

The listing this works from is the one `tools/disasm68k.py emit --verify`
reassembles byte for byte, so what is translated is exactly what was proved to
be code — and `coverage` says the machine runs nothing outside it.
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from disasm68k import analyse                    # noqa: E402
from hostcc import host_cc                       # noqa: E402
from recomp.m68kc import Codegen, fname          # noqa: E402

DEFAULT_ROM = "roms/Knuckles' Chaotix (JU) (32X) [!].32x"
CYCLES_PATH = "build/m68k_cycles.bin"


def read_cycles(path):
    """Musashi's 68000 cycle table, one byte per opcode word.

    Written by `build/m68kcycles`, which the Makefile builds from Musashi alone
    — see tools/m68kcycles.c for why the costs come from the interpreter rather
    than from a second reading of the manual. Missing it is a build-order
    mistake rather than something to paper over with a default, because a
    default would silently be the old flat clock again.
    """
    with open(path, "rb") as f:
        table = f.read()
    if len(table) != 0x10000:
        sys.exit("%s is %d bytes, expected 65536" % (path, len(table)))
    return table


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--rom", default=DEFAULT_ROM)
    p.add_argument("--out", default="build/m68k_recomp.c")
    p.add_argument("--cycles", default=CYCLES_PATH)
    p.add_argument("--build", action="store_true")
    args = p.parse_args()

    rom, az = analyse(args.rom)
    cg = Codegen(az, read_cycles(args.cycles))
    entries = sorted(az.funcs)

    body, protos = [], []
    for a in entries:
        protos.append(f"static uint32_t {fname(a)}(M68K *c, uint32_t entry);")
        body += cg.function(az.funcs[a]) + [""]

    # Address -> function, one row per block so a transfer to any known address
    # finds an owner and enters there. A block can belong to two functions that
    # share a tail; either will do, since a block's exits are explicit, so the
    # lowest-addressed owner is taken for a table that is the same every build.
    owner = {}
    for a in entries:
        for b in az.funcs[a].blocks:
            if b not in owner or a < owner[b]:
                owner[b] = a
    rows = sorted(owner.items())

    out = [
        "/* Generated by tools/recompile68k.py -- do not edit. */",
        '#include "m68000.h"',
        "",
        *protos,
        "",
        *body,
        "const M68KEntry m68k_functions[] = {",
        *[f"    {{ 0x{b:08X}u, {fname(a)} }}," for b, a in rows],
        "};",
        f"const unsigned m68k_function_count = {len(rows)};",
        "",
    ]
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(out))

    print(f"{len(entries):,} functions, {len(rows):,} blocks, "
          f"{len(az.code):,} instructions -> {args.out}")
    if cg.notes:
        print(f"    {len(cg.notes)} construct(s) outside the model:")
        seen = {}
        for addr, what in cg.notes:
            seen.setdefault(what.split()[0], []).append(addr)
        for what, addrs in sorted(seen.items(), key=lambda kv: -len(kv[1]))[:12]:
            print(f"      {what:<12} x{len(addrs):<5} first at 0x{addrs[0]:06X}")
    else:
        print("    every instruction translated")

    if args.build:
        obj = args.out.replace(".c", ".o")
        r = subprocess.run([host_cc(), "-O2", "-Wall", "-Isrc", "-c",
                            args.out, "-o", obj])
        if r.returncode:
            return 1
        print(f"    compiled -> {obj}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
