#!/usr/bin/env python3
"""Recompile the discovered SH-2 code to C.

  python3 tools/recompile.py            write build/sh2_recomp.c
  python3 tools/recompile.py --build    also compile it for this machine
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mars                                   # noqa: E402
from disasm import analyse                    # noqa: E402
from recomp.sh2c import Codegen, fname        # noqa: E402

DEFAULT_ROM = "roms/Knuckles' Chaotix (JU) (32X) [!].32x"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--rom", default=DEFAULT_ROM)
    p.add_argument("--out", default="build/sh2_recomp.c")
    p.add_argument("--build", action="store_true")
    args = p.parse_args()

    rom, h, img, az = analyse(args.rom)
    cg = Codegen(az, img)
    entries = sorted(az.funcs)

    body, protos = [], []
    for a in entries:
        protos.append(f"void {fname(a)}(SH2 *c);")
        body += cg.function(az.funcs[a]) + [""]

    # Address -> function table, so an indirect transfer can find its target.
    table = ["typedef struct { uint32_t addr; void (*fn)(SH2 *); } SH2Entry;",
             "const SH2Entry sh2_functions[] = {"]
    table += [f"    {{ 0x{a:08X}u, {fname(a)} }}," for a in entries]
    table += ["};",
              f"const unsigned sh2_function_count = {len(entries)};"]

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("/* Generated by tools/recompile.py -- do not edit. */\n")
        f.write('#include "sh2.h"\n\n')
        f.write("\n".join(protos) + "\n\n")
        f.write("\n".join(body) + "\n")
        f.write("\n".join(table) + "\n")

    print(f"{len(entries)} functions -> {args.out}")
    print(f"  escapes to other functions : {cg.escapes}")
    print(f"  unhandled constructs       : {len(cg.notes)}")
    for a, why in cg.notes[:10]:
        print(f"    0x{a:08X}  {why}")

    if args.build:
        obj = args.out.replace(".c", ".o")
        cmd = ["clang", "-c", "-O2", "-Isrc", "-Wall", "-Wno-unused-label",
               "-o", obj, args.out]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode:
            errs = [l for l in r.stderr.splitlines() if "error" in l]
            print(f"  COMPILE FAILED ({len(errs)} errors)")
            for l in errs[:15]:
                print("    " + l)
            return 1
        warn = [l for l in r.stderr.splitlines() if "warning" in l]
        size = os.path.getsize(obj)
        print(f"  compiled OK -> {obj} ({size:,} bytes, {len(warn)} warnings)")
        for l in warn[:8]:
            print("    " + l)
    return 0


if __name__ == "__main__":
    sys.exit(main())
